# Generated by Django 6.0.5 on 2026-05-07 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOFT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod',
            name='memory',
        ),
        migrations.AddField(
            model_name='prod',
            name='height',
            field=models.IntegerField(default=100, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='prod',
            name='length',
            field=models.IntegerField(default=100, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='prod',
            name='width',
            field=models.IntegerField(default=100, verbose_name='Ширина'),
        ),
        migrations.CreateModel(
            name='ProdPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото товара')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_photo', to='LOFT.prod', verbose_name='Фото товара')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
            },
        ),
    ]
