# Generated by Django 6.0.5 on 2026-05-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOFT', '0003_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone',
        ),
    ]
