# Generated by Django 6.0.5 on 2026-05-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOFT', '0005_prodmodel_customer_prod_prod_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodmodel',
            options={'verbose_name': 'Модель товара', 'verbose_name_plural': 'Модели товаров'},
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='customer',
            name='flat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Квартира №'),
        ),
        migrations.AddField(
            model_name='customer',
            name='home',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица'),
        ),
    ]
