# Generated by Django 6.0.5 on 2026-05-23 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOFT', '0006_alter_prodmodel_options_customer_city_customer_flat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='prod',
            name='prod_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prods', to='LOFT.prodmodel', verbose_name='Модель товара'),
        ),
    ]
