# Generated by Django 6.0.5 on 2026-05-26 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOFT', '0008_basket_basketitem_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='LOFT.customer', verbose_name='Покупатель'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='LOFT.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер получателя')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий к заказу')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('home', models.CharField(max_length=100, verbose_name='Дом')),
                ('flat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Квартира №')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOFT.city', verbose_name='Город')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippings', to='LOFT.customer', verbose_name='Покупатель')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOFT.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Доставку',
                'verbose_name_plural': 'Доставки',
            },
        ),
    ]
