# Generated by Django 6.0.5 on 2026-05-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOFT', '0009_region_alter_favorites_options_alter_basket_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contact_messages/', verbose_name='Прикрепленный файл'),
        ),
    ]
