# Generated by Django 6.0.5 on 2026-05-27 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOFT', '0011_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы покупателей'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='home',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='region',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='comment',
        ),
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Статус заказа получин ли'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Сумма заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='LOFT.shipping', verbose_name='Доставка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения заказа'),
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название твоара')),
                ('slug', models.CharField(max_length=150, verbose_name='Слаг твоара')),
                ('price', models.IntegerField(default=0, verbose_name='Цена твоара')),
                ('quantity', models.IntegerField(default=0, verbose_name='В кол-ве')),
                ('total_price', models.IntegerField(default=0, verbose_name='На сумму')),
                ('photo', models.ImageField(upload_to='products/', verbose_name='Фото товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='LOFT.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Товар в заказ',
                'verbose_name_plural': 'Заказов товары',
            },
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
