# Generated by Django 6.0.5 on 2026-05-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOFT', '0012_alter_order_options_remove_order_city_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('user', 'prod')},
        ),
    ]
