# Generated by Django 6.0.5 on 2026-05-28 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOFT', '0014_productrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='value',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
