# Generated by Django 6.0.5 on 2026-05-28 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOFT', '0015_alter_productrating_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='photo',
        ),
    ]
