# Generated by Django 6.0.5 on 2026-05-28 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOFT', '0016_remove_productorder_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='prod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='LOFT.prod', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
